# Generated by Django 5.2.8 on 2025-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='employees/'),
        ),
    ]
